#pragma once

#if defined(_MSVC_LANG)
#define STRING_MATH_CXX_STANDARD _MSVC_LANG
#else
#define STRING_MATH_CXX_STANDARD __cplusplus
#endif

#if STRING_MATH_CXX_STANDARD >= 202302L
#define STRING_MATH_HAS_CXX23 1
#else
#define STRING_MATH_HAS_CXX23 0
#endif

#if STRING_MATH_CXX_STANDARD >= 202002L
#define STRING_MATH_HAS_CXX20 1
#define STRING_MATH_HAS_CONSTEXPR_EVALUATION 1
#else
#define STRING_MATH_HAS_CXX20 0
#define STRING_MATH_HAS_CONSTEXPR_EVALUATION 0
#endif
